[versions]
jakarta-ee = "10.0.0"
junit = "5.13.1"
hamcrest = "3.0"
commons-lang = "3.20.0"

[libraries]
jakarta-bom = { module = "jakarta.platform:jakarta.jakartaee-bom", version.ref = "jakarta-ee" }

jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang" }
